language: go
before_install:
  - git clone --recursive git://github.com/apiaryio/drafter.git
  - cd drafter
  - git checkout v2.3.0-pre.2
  - ./configure
  - make drafter
  - export PATH=$PWD/bin:$PATH
  - cd ..
install:
  - go get -d -t -v
script:
  - go test -v
